apiVersion: v1
kind: Service #  Deployment or Service
metadata:
  name: udacity-api-feed
  labels:
    run: udacity-api-feed
spec:
  type: ClusterIP
  ports:
  - port: 8081
    protocol: TCP
  selector:
    run: udacity-api-feed