apiVersion: v1
kind: Service #  Deployment or Service
metadata:
  name: udacity-api-feed
  labels:
    run: udacity-api-feed
spec:
  type: NodePort
  ports:
  - port: 8081
    targetPort: 8082
    nodePort: 32701
    protocol: TCP
  selector:
    run: udacity-api-feed